# Generated by Django 3.0.3 on 2020-03-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_background', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('register_background', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('home_background', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
