# Generated by Django 3.0.3 on 2020-03-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_background'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background',
        ),
    ]
