# Generated by Django 3.0.3 on 2020-03-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='heading',
        ),
    ]
