# Generated by Django 3.0.3 on 2020-03-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200304_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Executives',
            new_name='Executive',
        ),
    ]
