# Generated by Django 3.0.4 on 2020-03-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200304_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('place_of_work', models.CharField(max_length=125)),
                ('subject', models.CharField(max_length=125)),
                ('message', models.TextField()),
            ],
        ),
    ]
