# Generated by Django 3.0.3 on 2020-03-04 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200304_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='home_background',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_background',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_background',
        ),
        migrations.CreateModel(
            name='BackgroundAmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_background', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('register_background', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('home_background', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
