# Generated by Django 3.0.3 on 2020-03-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200304_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackgroundAmin',
            new_name='BackgroundAdmin',
        ),
        migrations.AlterModelOptions(
            name='backgroundadmin',
            options={'verbose_name_plural': 'Backgrounds'},
        ),
    ]
