# Generated by Django 3.0.4 on 2020-03-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application Message', 'verbose_name_plural': 'Application Message'},
        ),
        migrations.AlterModelOptions(
            name='success',
            options={'verbose_name': 'Success Message', 'verbose_name_plural': 'Success Message'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'All Members'},
        ),
    ]
