# Generated by Django 3.0.4 on 2020-03-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='images',
            new_name='logo',
        ),
    ]
