# Generated by Django 3.0.4 on 2020-03-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200310_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success',
            name='message',
            field=models.TextField(max_length=75),
        ),
    ]
