# Generated by Django 3.0.4 on 2020-03-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200314_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='success',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='success',
            name='message',
            field=models.TextField(),
        ),
    ]
